apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-az
  namespace: dev
spec:
  volumeName: nd-pv
  storageClassName: ""
  accessModes:
    -  ReadWriteMany
  resources: 
    requests:
      storage: 100Gi