apiVersion: v1
kind: Pod

metadata:
  name: nginx
  namespace: ndapp
  labels:
    app: nginx

spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: az-storage-account
        mountPath: /nd
  
  volumes:
  - name: az-storage-account
    azureFile:
      secretName: azsecret
      shareName: ndfileshare-20260920


---

apiVersion: v1
kind: Pod
metadata:
  name: firefox
  namespace: ndapp
  labels:
    app: firefox
spec:
  containers:
    - name: firefox
      image: linuxserver/firefox:1.2404.1
