apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ndapp
spec:
  containers:
  - name: nginx
    image: nginx

---

apiVersion: v1
kind: Pod
metadata:
  name: firefox
  namespace: ndapp
spec:
  containers:
  - name: firefox
    image: linuxserver/firefox:1.2404.1