apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-firefox
  namespace: dev
  labels:
    app: rs-firefox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rs-firefox
  template:
    metadata:
      name: firefox
      namespace: dev
      labels:
        app: rs-firefox
    spec:
      volumes:
      - name: app-nginx-volume
        persistentVolumeClaim:
          claimName: pvc-az
      containers:
      - name: app-nginx
        image: linuxserver/firefox:1.2404.1
        volumeMounts:
        - name: app-nginx-volume
          mountPath : /app-nd


      

