apiVersion: v1
kind: Secret
metadata:
  name: azsecret
  namespace: dev
type: opaque
stringData:
  azurestorageaccountname: ndsa20260920
  azurestorageaccountkey: KGPbjBzGO2aUf1IJVwsRvxw83m8U86Yp90jdp1JYdwly7XUqwfsrp6UqJUx9nGUCocxOYy7/3N00+ASt12QwCQ==