apiVersion: v1
kind: Secret
metadata:
  name: azsecret
  namespace: dev
type: opaque
stringData:
  azurestorageaccountname: ndsa20260922
  azurestorageaccountkey: p9vXglGMblRd5loDxKOvIaRygDTyX2aCUyTyoZumOxoZ7tkr4GS6TADmmEY/7hA5I6wgfbzfqvHj+AStvj9SiQ==